# Generated by Django 3.2.7 on 2021-09-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_emails',
            options={'verbose_name': 'Upload Emails', 'verbose_name_plural': 'Upload Emails'},
        ),
    ]
