# Generated by Django 3.2.7 on 2021-09-08 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Add_Emails', '0002_alter_upload_emails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_emails',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upload_emails',
            name='remarks',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upload_emails',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
